# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPyy():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pyy(self):
    self.driver.get("https://leshuyun.com/login")
    self.driver.set_window_size(706, 528)
    self.driver.find_element(By.ID, "emailInp").click()
    self.driver.find_element(By.ID, "emailInp").click()
    self.driver.find_element(By.ID, "emailInp").click()
    element = self.driver.find_element(By.ID, "emailInp")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "点我签到~").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "确定").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "确定").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".user-center_header")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".user-center_header").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".text-danger > span").click()
    self.driver.find_element(By.ID, "emailInp").send_keys("706728206@qq.com")
    self.driver.find_element(By.ID, "emailPwdInp").send_keys("Kls123456")
  
